export const SERVICES = [
  "Combo cắt tóc nữ và gội đầu",
  "Combo cắt tóc nam và gội đầu",
  "Nhuộm tóc",
  "Làm tóc nổi bật",
  "Tạo kiểu tóc",
  "Làm móng tay",
  "Làm móng chân",
  "Sơn múng gel",
  "Đắp móng Gel cao cấp",
  "Đắp Gel nhũ",
  "Tẩy lông",
  "Massage",
  "Chăm sóc da mặt cơ bản",
  "Chăm sóc da vùng cổ trắng sáng",
  "Gội đầu, massage mặt",
];
